### ISSUE TITLE
How to set the server port gracefully?

### ISSUE THREAD

**Issue by guangmuzhu** [delphix/dsp#2]
The default protocol port is 8415 and is used in class ServerManagerImpl which sets its port when method start() is called.
I found no way to set the port of ServerManagerImpl except overriding it. Is there any other way to set the server port gracefully?
```java
    @Override
    public void start() {
        super.start();

        logger.info("Starting server manager");
        this.port = PORT;
        this.config = new ServerConfig();

        channelManager = new ServerTransportManager(this);
    }
```

Regards
Guangmu

**Comment by pengdai** [comment]
The DSP port 8415 is assigned by IANA. We encourage users to stick with this port, which is why we chose not to export setServerPort() in the ServerManager interface.

**Comment by guangmuzhu** [comment]
Thank you very much.
